// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2ISa7cbj15atveLvVxSuCkqBHI5R3vPI',
    appId: '1:38801012160:web:8dadcd42a8c4e1b0680425',
    messagingSenderId: '38801012160',
    projectId: 'piggyapp-de095',
    authDomain: 'piggyapp-de095.firebaseapp.com',
    storageBucket: 'piggyapp-de095.appspot.com',
    measurementId: 'G-R6NR4HL7SC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcwiX5CQcMsAbpk_MXjeH2YyicqldmxOI',
    appId: '1:38801012160:android:435c5cc3767d426d680425',
    messagingSenderId: '38801012160',
    projectId: 'piggyapp-de095',
    storageBucket: 'piggyapp-de095.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgvR7qrgI73Z1iZ3KrSBkCPuZ9_yQgOWM',
    appId: '1:38801012160:ios:c859b4d52e3d6a5f680425',
    messagingSenderId: '38801012160',
    projectId: 'piggyapp-de095',
    storageBucket: 'piggyapp-de095.appspot.com',
    iosClientId: '38801012160-50kuppee1va5gdbsnq3jsrqvgs24eoib.apps.googleusercontent.com',
    iosBundleId: 'com.example.piggywallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgvR7qrgI73Z1iZ3KrSBkCPuZ9_yQgOWM',
    appId: '1:38801012160:ios:c859b4d52e3d6a5f680425',
    messagingSenderId: '38801012160',
    projectId: 'piggyapp-de095',
    storageBucket: 'piggyapp-de095.appspot.com',
    iosClientId: '38801012160-50kuppee1va5gdbsnq3jsrqvgs24eoib.apps.googleusercontent.com',
    iosBundleId: 'com.example.piggywallet',
  );
}
